# Generated by Django 4.0.2 on 2022-02-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_persona_paciente_apellido1_paciente_apellido2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='incubadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.incubadora'),
        ),
    ]
