# Generated by Django 4.0.2 on 2022-04-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.persona'),
        ),
    ]
