# Generated by Django 4.0.2 on 2022-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
