# Generated by Django 4.0.2 on 2022-05-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_camara_puerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='activo',
        ),
    ]
